USE Pharmacy_DB;

-- This query retrieves the company name and address of the supplier
-- who provides the medication with the earliest expiration date in the Pharmacy_DB.
SELECT s.Company_name, s.Address
FROM Supplier s
JOIN Medication m ON s.Supplier_ID = m.Supplier_ID
WHERE m.Expiration_date = (SELECT MIN(Expiration_date) FROM Medication)
LIMIT 1;

-- This query retrieves the distinct names and emails of the staff members who made purchases on '2023-03-15'.
SELECT DISTINCT s.Name, s.Email
FROM Staff s
JOIN Purchase p ON s.Staff_ID = p.Staff_ID
WHERE p.Date_Purchased = '2023-03-15';

-- This query retrieves the distinct names and addresses of customers who have purchased Aspirin.
SELECT DISTINCT c.Name, c.Address
FROM Customer c
JOIN Purchase p ON c.Customer_ID = p.Customer_ID
JOIN Medication m ON p.Medication_ID = m.Medication_ID
WHERE m.Name = 'Aspirin';

-- This query retrieves the names, addresses, phone numbers, emails,
-- and purchase dates of customers who have purchased Ibuprofen within the past month.
SELECT c.Name, c.Address, c.Phone_number, c.Email, p.Date_Purchased
FROM Customer c
JOIN Purchase p ON c.Customer_ID = p.Customer_ID
JOIN Medication m ON p.Medication_ID = m.Medication_ID
WHERE m.Name = 'Ibuprofen' AND p.Date_Purchased >= DATE_SUB(NOW(), INTERVAL 1 MONTH);

-- This query retrieves the names of doctors who issued prescriptions
-- and the total count of prescriptions each doctor issued.
SELECT p.Issued_Doctor, COUNT(*) AS Prescription_Count
FROM Prescription p
GROUP BY p.Issued_Doctor;

-- This query retrieves the names of medications and 
-- the total count of prescriptions issued for each medication within the past month.
SELECT m.Name, COUNT(*) as Total_Prescriptions_Issued
FROM Medication m
JOIN Prescription p ON m.Medication_ID = p.Medication_ID
WHERE p.Issued_Date BETWEEN DATE_SUB(CURDATE(), INTERVAL 1 MONTH) AND CURDATE()
GROUP BY m.Medication_ID;

-- This query retrieves the names of staff members and the total revenue
-- generated by each staff member from purchases made within the past month.
SELECT st.Name, SUM(p.Price) AS Revenue
FROM Staff st
JOIN Purchase p ON st.Staff_ID = p.Staff_ID
WHERE p.Date_Purchased >= DATE_SUB(NOW(), INTERVAL 1 MONTH)
GROUP BY st.Staff_ID;

-- This query retrieves the names of medications and 
-- calculates the total quantity sold and the total price for each medication.
SELECT m.Name, SUM(p.Quantity) AS Total_Quantity, SUM(p.Price) AS Total_Price
FROM Medication m
JOIN Purchase p ON m.Medication_ID = p.Medication_ID
GROUP BY m.Name;

-- This query retrieves the names of medications and calculates the total revenue generated for each medication.
SELECT m.Name, SUM(p.Price) AS Total_Revenue
FROM Medication m
JOIN Purchase p ON m.Medication_ID = p.Medication_ID
GROUP BY m.Name;

-- This query retrieves the company names of suppliers and 
-- calculates the total revenue generated by each supplier from medication purchases.
SELECT s.Company_name, SUM(p.Price * p.Quantity) as Total_Revenue_Generated
FROM Supplier s
JOIN Medication m ON s.Supplier_ID = m.Supplier_ID
JOIN Purchase p ON m.Medication_ID = p.Medication_ID
GROUP BY s.Supplier_ID;

-- This query retrieves the locations of suppliers and calculates 
-- the total revenue generated by each location from medication purchases within the past year.
SELECT s.Location, SUM(p.Price * p.Quantity) as Total_Revenue_Generated
FROM Purchase p
JOIN Medication m ON p.Medication_ID = m.Medication_ID
JOIN Supplier s ON m.Supplier_ID = s.Supplier_ID
WHERE p.Date_Purchased BETWEEN DATE_SUB(CURDATE(), INTERVAL 1 YEAR) AND CURDATE()
GROUP BY s.Location;

-- This query retrieves the names of medications and calculates 
-- the total quantity sold and total revenue generated for each medication within the past year.
SELECT m.Name, SUM(p.Quantity) AS Total_Quantity_Sold, SUM(p.Price) AS Total_Revenue
FROM Medication m
JOIN Purchase p ON m.Medication_ID = p.Medication_ID
WHERE p.Date_Purchased >= DATE_SUB(NOW(), INTERVAL 1 YEAR)
GROUP BY m.Medication_ID;
